name: Deploy to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure AWS credentials using GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Log in to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 676206932988.dkr.ecr.us-east-1.amazonaws.com

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t mileston-landing:latest .

      # Tag the image for ECR
      - name: Tag Docker image
        run: |
          docker tag mileston-landing:latest ${{ secrets.AWS_ECR_REPOSITORY }}:latest

      # Push the image to ECR
      - name: Push Docker image
        run: |
          docker push ${{ secrets.AWS_ECR_REPOSITORY }}:latest
